In [1]:
import sys
import copy
import matplotlib
import numpy as np
import pandas as pd
import networkx as nx
from matplotlib import pyplot as plt

sys.path.append("../../../")

from graph_dynamics.networks import communities
from graph_dynamics.dynamics import GraphPathsHandlers
from graph_dynamics.utils import graph_paths_visualization
from graph_dynamics.dynamics import GenerativeDynamicsCommunities


matplotlib.rcParams['ps.useafm'] = True
matplotlib.rcParams['text.usetex'] = True
matplotlib.rcParams['pdf.use14corefonts'] = True

%matplotlib inline 

In [2]:
matplotlib.style.use('seaborn-talk')
colors = []
for a in plt.style.library['bmh']['axes.prop_cycle']:
    colors.append(a["color"])

# Parameters

In [3]:
forest_fire_communities_parameters = {0:{"BurnExpFireP":False,
                                         "StartNNodes":1,
                                         "ForwBurnProb":0.2,
                                         "BackBurnProb":0.32,
                                         "DecayProb":1.0,
                                         "Take2AmbasPrb":0.,
                                         "OrphanPrb": 0.},
                                      1:{"BurnExpFireP":False,
                                         "StartNNodes":1,
                                         "ForwBurnProb":0.2,
                                         "BackBurnProb":0.32,
                                         "DecayProb":1.0,
                                         "Take2AmbasPrb":0.,
                                         "OrphanPrb": 0.},
                                      2:{"BurnExpFireP":False,
                                         "StartNNodes":1,
                                         "ForwBurnProb":0.7,
                                         "BackBurnProb":0.72,
                                         "DecayProb":1.0,
                                         "Take2AmbasPrb":0.,
                                         "OrphanPrb": 0.},
                                      3:{"BurnExpFireP":False,
                                         "StartNNodes":1,
                                         "ForwBurnProb":0.2,
                                         "BackBurnProb":0.32,
                                         "DecayProb":1.0,
                                         "Take2AmbasPrb":0.,
                                         "OrphanPrb": 0.}}

numberOfCommunitiesAndNoise = len(forest_fire_communities_parameters.keys())

numberOfSteps = 10
#back ground evolution
timeSeriesCommunity0 = np.ones(numberOfSteps)*2
timeSeriesCommunity0[0] = 0

timeSeriesCommunity1 = np.ones(numberOfSteps)*2
timeSeriesCommunity1[0] = 30

timeSeriesCommunity2 = np.ones(numberOfSteps)*3
timeSeriesCommunity2[0] = 30

timeSeriesCommunity3 = np.ones(numberOfSteps)*4
timeSeriesCommunity3[0] = 30

timeSeriesOfCommunities = {0:timeSeriesCommunity0,
                           1:timeSeriesCommunity1,
                           2:timeSeriesCommunity2,
                           3:timeSeriesCommunity3}

#the initial size of the community is that as defined by the time series
numberOfNodesPerCommunities = [timeSeriesOfCommunities[c][0] for c in range(1,numberOfCommunitiesAndNoise)]
numberOfBridgesPerCommunity = [5,5,5]
barabasiParameter = 3
initial_graph, subGraphs,Q,bridgesInCommunity = communities.barabasiAlbertCommunities(numberOfNodesPerCommunities, 
                                                      numberOfBridgesPerCommunity, 
                                                      barabasiParameter)
initial_communities = {c:subGraphs[c-1].nodes() for c in range(1,numberOfCommunitiesAndNoise)}
initial_communities[0]=[]

In [4]:
numberOfNodesPerCommunities

[30.0, 30.0, 30.0]

In [5]:
dynamics = GenerativeDynamicsCommunities.CommunitiesForestFire(initial_graph,initial_communities,forest_fire_communities_parameters,timeSeriesOfCommunities)

In [6]:
graph_series, relabeling, initial_relabeling = dynamics.generate_graphs_series(10)

In [7]:
len(graph_series[0])

10

In [24]:
np.array(graph_series[0][1].nodes())[::-1]

array([91, 90, 89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 77, 76, 75,
       74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60, 59, 58,
       57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41,
       40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24,
       23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,
        6,  5,  4,  3,  2,  1,  0])

In [9]:
relabeling

{1: [{30: 90, 31: 91},
  {32: 101, 33: 102},
  {34: 112, 35: 113},
  {36: 123, 37: 124},
  {38: 134, 39: 135},
  {40: 145, 41: 146},
  {42: 156, 43: 157},
  {44: 167, 45: 168},
  {46: 178, 47: 179}],
 2: [{30: 92, 31: 93, 32: 94},
  {33: 103, 34: 104, 35: 105},
  {36: 114, 37: 115, 38: 116},
  {39: 125, 40: 126, 41: 127},
  {42: 136, 43: 137, 44: 138},
  {45: 147, 46: 148, 47: 149},
  {48: 158, 49: 159, 50: 160},
  {51: 169, 52: 170, 53: 171},
  {54: 180, 55: 181, 56: 182}],
 3: [{30: 95, 31: 96, 32: 97, 33: 98},
  {34: 106, 35: 107, 36: 108, 37: 109},
  {38: 117, 39: 118, 40: 119, 41: 120},
  {42: 128, 43: 129, 44: 130, 45: 131},
  {46: 139, 47: 140, 48: 141, 49: 142},
  {50: 150, 51: 151, 52: 152, 53: 153},
  {54: 161, 55: 162, 56: 163, 57: 164},
  {58: 172, 59: 173, 60: 174, 61: 175},
  {62: 183, 63: 184, 64: 185, 65: 186}]}

In [10]:
c = 1
for time in range(1,numberOfSteps-1):
    print time
    new_community_graph = graph_series[c][time]
    relabeled_graph = nx.relabel_nodes(new_community_graph,relabeling[c][time-1])
    #print relabeled_graph.edge

1
2
3
4
5
6
7
8


In [11]:
fullTimeSeriesStack = np.array([timeSeriesOfCommunities[c] for c in range(0,numberOfCommunitiesAndNoise)])
fullTimeSeriesStackCum = fullTimeSeriesStack.cumsum(axis=1)

fullTimeSeries = fullTimeSeriesStack.sum(axis=0)
cumFullTimeSeries = fullTimeSeries.cumsum()

In [12]:
cumFullTimeSeries

array([  90.,  101.,  112.,  123.,  134.,  145.,  156.,  167.,  178.,  189.])

In [13]:
fullTimeSeriesStack

array([[  0.,   2.,   2.,   2.,   2.,   2.,   2.,   2.,   2.,   2.],
       [ 30.,   2.,   2.,   2.,   2.,   2.,   2.,   2.,   2.,   2.],
       [ 30.,   3.,   3.,   3.,   3.,   3.,   3.,   3.,   3.,   3.],
       [ 30.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.]])

In [14]:
relabeling = {c:[] for c in range(1,numberOfCommunitiesAndNoise)}
totalInitialNumberOfNodes = cumFullTimeSeries[0]
for time in range(1,numberOfSteps):
    accuPerCommunity = 0
    print "time",time
    lower_border = int(cumFullTimeSeries[time-1])
    for c in range(1,numberOfCommunitiesAndNoise):
        #take new node created in the individual dynamics
        print "community ",c
        newNodesInCommnity = range(int(fullTimeSeriesStackCum[c][time-1]),int(fullTimeSeriesStackCum[c][time])) 
        numberOfNewNodes = int(fullTimeSeriesStack[c][time])
        print "totalInitialNumberOfNodes ",int(totalInitialNumberOfNodes)
        upper_border = lower_border + numberOfNewNodes
        newNames = range(lower_border, upper_border)
        print "upper border ",upper_border
        print "newNames ",newNames 
        print "#####"
        instantaneous_relabeling = dict(zip(newNodesInCommnity,newNames))
        relabeling[c].append(instantaneous_relabeling)
        
        lower_border += numberOfNewNodes
        totalInitialNumberOfNodes += accuPerCommunity 
    print "\n"

time 1
community  1
totalInitialNumberOfNodes  90
upper border  92
newNames  [90, 91]
#####
community  2
totalInitialNumberOfNodes  90
upper border  95
newNames  [92, 93, 94]
#####
community  3
totalInitialNumberOfNodes  90
upper border  99
newNames  [95, 96, 97, 98]
#####


time 2
community  1
totalInitialNumberOfNodes  90
upper border  103
newNames  [101, 102]
#####
community  2
totalInitialNumberOfNodes  90
upper border  106
newNames  [103, 104, 105]
#####
community  3
totalInitialNumberOfNodes  90
upper border  110
newNames  [106, 107, 108, 109]
#####


time 3
community  1
totalInitialNumberOfNodes  90
upper border  114
newNames  [112, 113]
#####
community  2
totalInitialNumberOfNodes  90
upper border  117
newNames  [114, 115, 116]
#####
community  3
totalInitialNumberOfNodes  90
upper border  121
newNames  [117, 118, 119, 120]
#####


time 4
community  1
totalInitialNumberOfNodes  90
upper border  125
newNames  [123, 124]
#####
community  2
totalInitialNumberOfNodes  90
upper bord

In [15]:
relabeling

{1: [{30: 90, 31: 91},
  {32: 101, 33: 102},
  {34: 112, 35: 113},
  {36: 123, 37: 124},
  {38: 134, 39: 135},
  {40: 145, 41: 146},
  {42: 156, 43: 157},
  {44: 167, 45: 168},
  {46: 178, 47: 179}],
 2: [{30: 92, 31: 93, 32: 94},
  {33: 103, 34: 104, 35: 105},
  {36: 114, 37: 115, 38: 116},
  {39: 125, 40: 126, 41: 127},
  {42: 136, 43: 137, 44: 138},
  {45: 147, 46: 148, 47: 149},
  {48: 158, 49: 159, 50: 160},
  {51: 169, 52: 170, 53: 171},
  {54: 180, 55: 181, 56: 182}],
 3: [{30: 95, 31: 96, 32: 97, 33: 98},
  {34: 106, 35: 107, 36: 108, 37: 109},
  {38: 117, 39: 118, 40: 119, 41: 120},
  {42: 128, 43: 129, 44: 130, 45: 131},
  {46: 139, 47: 140, 48: 141, 49: 142},
  {50: 150, 51: 151, 52: 152, 53: 153},
  {54: 161, 55: 162, 56: 163, 57: 164},
  {58: 172, 59: 173, 60: 174, 61: 175},
  {62: 183, 63: 184, 64: 185, 65: 186}]}