In [10]:
import os
import sys
import numpy as np
import networkx as nx
from scipy.stats import gamma
from matplotlib import pyplot as plt

In [15]:
gd_folder = "/home/cesar/Desktop/Doctorado/Projects/Networks/Dynamics/Simulations/"
identifier_string = "palla_dynamics_test"
foldername = gd_folder + identifier_string + "_gd/"

In [17]:
"dynamics_identifier_gGD_1000_.gd".split("_")

['dynamics', 'identifier', 'gGD', '1000', '.gd']

In [38]:
N = 123
steps_in_memory = 20

A = np.concatenate([np.repeat(steps_in_memory,N / steps_in_memory),np.array([N % steps_in_memory])])

print 

edge_list = [(2,3),(5,7)]
A 

array([20, 20, 20, 20, 20, 20,  3])

In [28]:
str(edge_list[0])

'(2, 3)'

In [31]:
"\n".join(["{0} {1}".format(a[0],a[1]) for a in edge_list])

'2 3\n5 7'

In [16]:
if not os.path.exists(foldername):
    os.makedirs(foldername)

# Some Basics Graphs Stuff

In [39]:
graph = nx.Graph()

In [40]:
graph.add_edge(1,2,weight=2)
w = graph.edge[1][2]["weight"]
graph.add_edge(1,2,weight=w+1)

In [46]:
mydir = "/home/cesar/Desktop/Doctorado/Projects/Networks/Dynamics/Simulations/palla_dynamics_test_gd/"

In [48]:
nx.write_edgelist(graph,mydir+"test.gd")

In [18]:
gamma.rvs(1.,0.2)

0.2501848628887975

In [6]:
A = {1:3}
1 in A

True

In [7]:
A.keys()

[1]

In [16]:
graph.edge

{1: {2: {'weight': 3}}, 2: {1: {'weight': 3}}}

In [9]:
A = np.ones((5,5))*0.2

In [10]:
from scipy.stats import bernoulli

In [15]:
B = bernoulli.rvs(A)

In [12]:
A.diagonal()

array([ 0.2,  0.2,  0.2,  0.2,  0.2])

In [16]:
A = B.diagonal()

In [23]:
A[np.diag_indices(A.shape[0])] = B.diagonal()

In [25]:
A

array([[ 0. ,  0.2,  0.2,  0.2,  0.2],
       [ 0.2,  0. ,  0.2,  0.2,  0.2],
       [ 0.2,  0.2,  0. ,  0.2,  0.2],
       [ 0.2,  0.2,  0.2,  0. ,  0.2],
       [ 0.2,  0.2,  0.2,  0.2,  1. ]])

In [2]:
bara = nx.barabasi_albert_graph(100,4)

In [32]:
bara.degree()

{0: 11,
 1: 23,
 2: 16,
 3: 11,
 4: 37,
 5: 20,
 6: 32,
 7: 16,
 8: 15,
 9: 18,
 10: 15,
 11: 21,
 12: 22,
 13: 19,
 14: 6,
 15: 9,
 16: 7,
 17: 11,
 18: 10,
 19: 8,
 20: 13,
 21: 9,
 22: 14,
 23: 9,
 24: 5,
 25: 9,
 26: 7,
 27: 5,
 28: 5,
 29: 5,
 30: 7,
 31: 10,
 32: 4,
 33: 5,
 34: 9,
 35: 10,
 36: 6,
 37: 9,
 38: 8,
 39: 6,
 40: 11,
 41: 8,
 42: 5,
 43: 4,
 44: 5,
 45: 5,
 46: 4,
 47: 5,
 48: 5,
 49: 5,
 50: 7,
 51: 6,
 52: 5,
 53: 5,
 54: 4,
 55: 4,
 56: 5,
 57: 5,
 58: 5,
 59: 4,
 60: 4,
 61: 4,
 62: 5,
 63: 7,
 64: 4,
 65: 5,
 66: 4,
 67: 7,
 68: 4,
 69: 5,
 70: 6,
 71: 6,
 72: 5,
 73: 5,
 74: 6,
 75: 4,
 76: 4,
 77: 5,
 78: 4,
 79: 4,
 80: 5,
 81: 4,
 82: 4,
 83: 4,
 84: 4,
 85: 4,
 86: 4,
 87: 4,
 88: 4,
 89: 4,
 90: 4,
 91: 4,
 92: 4,
 93: 4,
 94: 4,
 95: 4,
 96: 4,
 97: 4,
 98: 4,
 99: 4}