In [1]:
import os
import sys
import numpy as np
import networkx as nx
from scipy.stats import gamma
from matplotlib import pyplot as plt

In [2]:
gd_folder = "/home/cesar/Desktop/Doctorado/Projects/Networks/Dynamics/Simulations/"
identifier_string = "palla_dynamics_test"
foldername = gd_folder + identifier_string + "_gd/"

In [3]:
"dynamics_identifier_gGD_1000_.gd".split("_")

['dynamics', 'identifier', 'gGD', '1000', '.gd']

In [4]:
A = nx.barabasi_albert_graph(20,3)

In [112]:
A = range(30)


window = 3
rolling = True

def createWindows(ALL_TIME_INDEXES,window,rolling):
    """
    indexes to be selected for analysis
    """
    maxA = max(ALL_TIME_INDEXES)
    minA = min(ALL_TIME_INDEXES)
    if ALL_TIME_INDEXES != range(minA,maxA+1):
        print "Missing graphs"
        raise Exception
    
    WINDOWS = []
    if not rolling:
        steps = range(minA,maxA,window)
        steps.append(maxA)
        for initial_window_index in steps[:-1]:
            window_list = range(initial_window_index,initial_window_index+window)
            if window_list[-1] <= maxA:
                WINDOWS.append(window_list)
    else:
        for a in ALL_TIME_INDEXES[:-window]:
            window_list = range(a,a+window+1)
            if window_list[-1] <= maxA:
                WINDOWS.append(window_list)
    return WINDOWS

In [129]:
A = range(0,20)
WINDOWS = createWindows(A,2,True)

In [130]:
WINDOWS

[[0, 1, 2],
 [1, 2, 3],
 [2, 3, 4],
 [3, 4, 5],
 [4, 5, 6],
 [5, 6, 7],
 [6, 7, 8],
 [7, 8, 9],
 [8, 9, 10],
 [9, 10, 11],
 [10, 11, 12],
 [11, 12, 13],
 [12, 13, 14],
 [13, 14, 15],
 [14, 15, 16],
 [15, 16, 17],
 [16, 17, 18],
 [17, 18, 19]]

In [98]:
#WINDOWS[0].pop(0)

7

In [99]:
WINDOWS

[[8, 9, 10, 11, 12, 13],
 [8, 9, 10, 11, 12, 13, 14],
 [9, 10, 11, 12, 13, 14, 15],
 [10, 11, 12, 13, 14, 15, 16],
 [11, 12, 13, 14, 15, 16, 17],
 [12, 13, 14, 15, 16, 17, 18],
 [13, 14, 15, 16, 17, 18, 19]]

In [38]:
N = 123
steps_in_memory = 20

A = np.concatenate([np.repeat(steps_in_memory,N / steps_in_memory),np.array([N % steps_in_memory])])

print 

edge_list = [(2,3),(5,7)]
A 

array([20, 20, 20, 20, 20, 20,  3])

In [28]:
str(edge_list[0])

'(2, 3)'

In [31]:
"\n".join(["{0} {1}".format(a[0],a[1]) for a in edge_list])

'2 3\n5 7'

In [16]:
if not os.path.exists(foldername):
    os.makedirs(foldername)

# Some Basics Graphs Stuff

In [39]:
graph = nx.Graph()

In [40]:
graph.add_edge(1,2,weight=2)
w = graph.edge[1][2]["weight"]
graph.add_edge(1,2,weight=w+1)

In [46]:
mydir = "/home/cesar/Desktop/Doctorado/Projects/Networks/Dynamics/Simulations/palla_dynamics_test_gd/"

In [48]:
nx.write_edgelist(graph,mydir+"test.gd")

In [18]:
gamma.rvs(1.,0.2)

0.2501848628887975

In [6]:
A = {1:3}
1 in A

True

In [7]:
A.keys()

[1]

In [16]:
graph.edge

{1: {2: {'weight': 3}}, 2: {1: {'weight': 3}}}

In [9]:
A = np.ones((5,5))*0.2

In [10]:
from scipy.stats import bernoulli

In [15]:
B = bernoulli.rvs(A)

In [12]:
A.diagonal()

array([ 0.2,  0.2,  0.2,  0.2,  0.2])

In [16]:
A = B.diagonal()

In [23]:
A[np.diag_indices(A.shape[0])] = B.diagonal()

In [25]:
A

array([[ 0. ,  0.2,  0.2,  0.2,  0.2],
       [ 0.2,  0. ,  0.2,  0.2,  0.2],
       [ 0.2,  0.2,  0. ,  0.2,  0.2],
       [ 0.2,  0.2,  0.2,  0. ,  0.2],
       [ 0.2,  0.2,  0.2,  0.2,  1. ]])

In [3]:
bara = nx.barabasi_albert_graph(100,4)

In [8]:
nx.write_edgelist?