In [1]:
import os
import sys
import numpy as np
import networkx as nx
from scipy.stats import gamma
from matplotlib import pyplot as plt

In [2]:
gd_folder = "/home/cesar/Desktop/Doctorado/Projects/Networks/Dynamics/Simulations/"
identifier_string = "palla_dynamics_test"
foldername = gd_folder + identifier_string + "_gd/"

In [17]:
"dynamics_identifier_gGD_1000_.gd".split("_")

['dynamics', 'identifier', 'gGD', '1000', '.gd']

In [38]:
N = 123
steps_in_memory = 20

A = np.concatenate([np.repeat(steps_in_memory,N / steps_in_memory),np.array([N % steps_in_memory])])

print 

edge_list = [(2,3),(5,7)]
A 

array([20, 20, 20, 20, 20, 20,  3])

In [28]:
str(edge_list[0])

'(2, 3)'

In [31]:
"\n".join(["{0} {1}".format(a[0],a[1]) for a in edge_list])

'2 3\n5 7'

In [16]:
if not os.path.exists(foldername):
    os.makedirs(foldername)

# Some Basics Graphs Stuff

In [39]:
graph = nx.Graph()

In [40]:
graph.add_edge(1,2,weight=2)
w = graph.edge[1][2]["weight"]
graph.add_edge(1,2,weight=w+1)

In [46]:
mydir = "/home/cesar/Desktop/Doctorado/Projects/Networks/Dynamics/Simulations/palla_dynamics_test_gd/"

In [48]:
nx.write_edgelist(graph,mydir+"test.gd")

In [18]:
gamma.rvs(1.,0.2)

0.2501848628887975

In [6]:
A = {1:3}
1 in A

True

In [7]:
A.keys()

[1]

In [16]:
graph.edge

{1: {2: {'weight': 3}}, 2: {1: {'weight': 3}}}

In [9]:
A = np.ones((5,5))*0.2

In [10]:
from scipy.stats import bernoulli

In [15]:
B = bernoulli.rvs(A)

In [12]:
A.diagonal()

array([ 0.2,  0.2,  0.2,  0.2,  0.2])

In [16]:
A = B.diagonal()

In [23]:
A[np.diag_indices(A.shape[0])] = B.diagonal()

In [25]:
A

array([[ 0. ,  0.2,  0.2,  0.2,  0.2],
       [ 0.2,  0. ,  0.2,  0.2,  0.2],
       [ 0.2,  0.2,  0. ,  0.2,  0.2],
       [ 0.2,  0.2,  0.2,  0. ,  0.2],
       [ 0.2,  0.2,  0.2,  0.2,  1. ]])

In [3]:
bara = nx.barabasi_albert_graph(100,4)

In [8]:
nx.write_edgelist?